language: java
jdk:
 - openjdk8

branches:
 only:
   - main 

# Travis CI 서버의 Home
cache:
 directories:
   - '$HOME/.m2/repository'
   - '$HOME/.gradle'

before install:
  - chmod +x gradlew
     
script: "./gradlew clean build"

before_deploy:
    - zip -r freelec-springboot2_1-webservice * # CodeDeploy는 jar파일을 인식하지 못하므로 zip한다
    - mkdir -p deploy
    - mv freelec-springboot2_1-webservice.zip deploy/freelec-springboot2_1-webservice.zip

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: freelec-springboot-build
    region: ap-northeast-2
    skip_cleanup: true
    acl: private
    local_dir: deploy
    wait-until-deployed: true
     
# CI 실행 완료 시 메일로 알람
notifications:
 email:
   recipients: 
     - gmdals45@gmail.com
