spring:
  h2:
    console:
      enabled: false
      path: /h2-console
  datasource:
    url: jdbc:mariadb://springboot-webservices-2022.cvokj1cptwnp.us-east-1.rds.amazonaws.com:3306/springboot_webservices_2022
    username: admin
    password: tlsRbqlqjs1!
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: none

  profiles:
    include: oauth, real-db