spring:
  application:
    name: board-service
  cloud:
    config:
      #uri: http://172.31.86.214:8071
      uri: http://54.84.19.74:8071

logging:
  level:
    com.netflix: WARN
    org.springframework.web: WARN
    com.optimagrowth: DEBUG
